# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-06 10:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitapp', '0004_auto_20191106_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.CharField(blank=True, max_length=1000, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.CharField(blank=True, max_length=1000, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='groups',
            field=models.CharField(blank=True, max_length=1000, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.png', upload_to=b''),
        ),
    ]
