# Generated by Django 2.2.6 on 2019-11-06 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitapp', '0006_auto_20191106_1541'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='transaction',
        ),
    ]
