# Generated by Django 2.2.6 on 2019-11-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitapp', '0007_auto_20191106_1547'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='trans',
        ),
    ]
