# Generated by Django 2.2.6 on 2019-11-06 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitapp', '0008_auto_20191106_1705'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='UserProfile',
        ),
    ]
