# Generated by Django 2.2.6 on 2019-11-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitapp', '0009_auto_20191106_1733'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='Groups',
        ),
    ]
