# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-06 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitapp', '0010_auto_20191106_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(default='default_username', max_length=30, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
