# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-06 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitapp', '0011_auto_20191106_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(max_length=30),
        ),
    ]
