# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-06 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitapp', '0013_auto_20191106_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
