# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-06 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitapp', '0014_auto_20191106_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user_name',
        ),
    ]
