# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-06 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitapp', '0015_auto_20191106_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=b''),
        ),
    ]
