# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-06 22:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitapp', '0016_auto_20191106_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.CharField(blank=True, max_length=1000, null=True, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='groups',
            field=models.CharField(blank=True, max_length=1000, null=True, validators=[django.core.validators.int_list_validator]),
        ),
    ]
